// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface GeoResponse {
  type: string
  query: string[]
  features: Feature[]
  attribution: string
}

export interface Feature {
  id: string
  type: string
  place_type: string[]
  relevance: number
  properties: Properties
  text: string
  place_name: string
  matching_text: string
  matching_place_name: string
  center: number[]
  geometry: Geometry
  address: string
  context: Context[]
}

export interface Context {
  id: string
  text: string
  wikidata?: null | string
  short_code?: ShortCode
}

export enum ShortCode {
  Us = 'us',
  UsIL = 'US-IL'
}

export interface Geometry {
  type: string
  coordinates: number[]
  interpolated?: boolean
  omitted?: boolean
}

export interface Properties {}
